#!/bin/bash

read -p "Instalar las commons ? (y/N)" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
	git clone https://github.com/sisoputnfrba/so-commons-library.git
	cd so-commons-library
	sudo make install
	cd ..
fi

cd dalibrary
sudo make install
cd ..

cd KNL/src
make
mv KNL ./../
cd ..
cd ..

cd LFS/src
make
mv LFS ./../
cd ..
cd ..

cd MEM/src
make
mv MEM ./../
cd ..
cd ..

clear

echo "Tutti compilado"
